In [1]:
# Blink Conversion: Frame to Seconds
# Jeremy Delahanty

In [54]:
from pathlib import Path
import pandas as pd
import tables

basepath = Path("Y:/specialk/learned_helplessness/LHE011/twop/")
mergedpath = Path("Y:/specialk/learned_helplessness/LHE014/twop/20210606/20210606_LHE014_plane0_merged.h5")

In [58]:
dates = ["20210608", "20210611", "20210612"]

In [64]:
for date in dates:
    date_path = basepath / date
    blink_glob = date_path.glob("*.csv")
    for i in blink_glob:
        print(i)
        blinks = pd.read_csv(i, header=None)
        blinks.columns = ["frame"]
        blinks["seconds"] = round(blinks.frame / 30, 2)
        print(blinks)
        
#         blinks.to_csv(str(date_path) + "blinks_seconds.csv")

In [56]:
pd.read_hdf(mergedpath, key="stimulus_timestamps")

,trial_type,Speaker_on,Speaker_off,Airpuff_on,Airpuff_off,Liquid_on,Liquid_off
trial,,,,,,,
Trial_1,Liquid_1,20.342,23.477,NaN,NaN,23.477,23.678
Trial_2,Liquid_2,42.989,44.222,NaN,NaN,44.222,44.423
Trial_3,Liquid_3,77.628,80.587,NaN,NaN,80.587,80.788
Trial_4,Airpuff_1,109.641,110.882,110.882,110.981,NaN,NaN
Trial_5,Liquid_4,130.270,134.797,NaN,NaN,134.797,134.998
Trial_6,Liquid_5,161.285,162.501,NaN,NaN,162.501,162.701
Trial_7,Liquid_6,188.469,191.993,NaN,NaN,191.994,192.193
Trial_8,Liquid_7,223.549,227.494,NaN,NaN,227.494,227.693
Trial_9,Liquid_8,260.398,261.965,NaN,NaN,261.965,262.165
Trial_10,Liquid_9,293.794,298.657,NaN,NaN,298.658,298.857
Trial_11,Liquid_10,329.737,331.437,NaN,NaN,331.438,331.638
Trial_12,Airpuff_2,357.696,360.171,360.172,360.271,NaN,NaN
Trial_13,Airpuff_3,383.984,387.985,387.985,388.085,NaN,NaN
Trial_14,Airpuff_4,413.821,418.064,418.064,418.164,NaN,NaN
Trial_15,Liquid_11,448.002,452.763,NaN,NaN,452.763,452.963
Trial_16,Airpuff_5,476.987,481.264,481.265,481.365,NaN,NaN
Trial_17,Liquid_12,499.342,500.787,NaN,NaN,500.787,500.987
Trial_18,Liquid_13,524.147,525.649,NaN,NaN,525.649,525.849
Trial_19,Liquid_14,547.463,549.140,NaN,NaN,549.141,549.340
Trial_20,Liquid_15,582.536,585.339,NaN,NaN,585.340,585.539
Trial_21,Airpuff_6,607.436,610.703,610.704,610.803,NaN,NaN
Trial_22,Liquid_16,638.041,639.369,NaN,NaN,639.370,639.569
Trial_23,Liquid_17,669.539,672.132,NaN,NaN,672.132,672.332
Trial_24,Airpuff_7,692.675,694.480,694.481,694.581,NaN,NaN
Trial_25,Airpuff_8,718.981,721.251,721.251,721.352,NaN,NaN
Trial_26,Airpuff_9,740.291,743.694,743.695,743.795,NaN,NaN
Trial_27,Liquid_18,767.955,772.146,NaN,NaN,772.147,772.347
Trial_28,Liquid_19,799.687,803.646,NaN,NaN,803.646,803.846
Trial_29,Liquid_20,837.061,840.193,NaN,NaN,840.193,840.394
Trial_30,Liquid_21,873.351,875.155,NaN,NaN,875.156,875.356
Trial_31,Liquid_22,907.569,911.097,NaN,NaN,911.097,911.298
Trial_32,Liquid_23,942.302,945.005,NaN,NaN,945.006,945.206
Trial_33,Liquid_24,972.349,976.676,NaN,NaN,976.676,976.876
Trial_34,Liquid_25,1009.617,1013.299,NaN,NaN,1013.300,1013.501
Trial_35,Liquid_26,1033.829,1035.677,NaN,NaN,1035.678,1035.877
Trial_36,Liquid_27,1056.614,1059.620,NaN,NaN,1059.621,1059.821
Trial_37,Airpuff_10,1089.461,1092.510,1092.511,1092.610,NaN,NaN
Trial_38,Liquid_28,1115.212,1118.298,NaN,NaN,1118.299,1118.500
Trial_39,Liquid_29,1140.795,1143.885,NaN,NaN,1143.885,1144.085
Trial_40,Liquid_30,1163.426,1168.386,NaN,NaN,1168.386,1168.585

In [57]:
x = pd.read_csv("Y:/specialk/learned_helplessness/LHE011/twop/20210606blinks_seconds.csv", index_col=0)

offset = abs(110.13 - 110.9) + .1
print(offset)

x["corrected"] = x.seconds + offset

print(x)

x.to_csv("Y:/specialk/learned_helplessness/LHE014/twop/20210606/corrected_blinks.csv")

0.8700000000000102
    frame  seconds  corrected
0    1850    61.67      62.54
1    3304   110.13     111.00
2   10783   359.43     360.30
3   11618   387.27     388.14
4   12520   417.33     418.20
5   14416   480.53     481.40
6   17813   593.77     594.64
7   17816   593.87     594.74
8   17821   594.03     594.90
9   18299   609.97     610.84
10  20813   693.77     694.64
11  21616   720.53     721.40
12  22061   735.37     736.24
13  22067   735.57     736.44
14  22072   735.73     736.60
15  22289   742.97     743.84
16  32754  1091.80    1092.67